timestamp: '2025-08-22T11:48:04'
joints:
  shoulder_pan_joint:
    min:
      ticks: 870
      speed: 0
      load: -3026
    center:
      ticks: 1292
      speed: 0
      load: 0
    max:
      ticks: 2682
      speed: 0
      load: 0
    home:
      ticks: 2048
      speed: 2048
      load: 2475
  shoulder_lift_joint:
    min:
      ticks: 98
      speed: 97
      load: 0
    center:
      ticks: 1922
      speed: 1277
      load: 0
    max:
      ticks: 3016
      speed: -50
      load: -1
    home:
      ticks: 907
      speed: 2048
      load: 0
  elbow_joint:
    min:
      ticks: 977
      speed: 0
      load: 0
    center:
      ticks: 2132
      speed: 50
      load: 0
    max:
      ticks: 4049
      speed: 0
      load: 870
    home:
      ticks: 3139
      speed: 0
      load: 0
  wrist_pitch_joint:
    min:
      ticks: 706
      speed: 0
      load: 0
    center:
      ticks: 1926
      speed: 1252
      load: -896
    max:
      ticks: 2816
      speed: 0
      load: 0
    home:
      ticks: 2475
      speed: 0
      load: 0
  wrist_roll_joint:
    min:
      ticks: 11
      speed: 0
      load: 0
    center:
      ticks: 2058
      speed: 0
      load: 0
    max:
      ticks: 4030
      speed: -1
      load: -3006
    home:
      ticks: 2017
      speed: 0
      load: 0
  gripper_joint:
    min:
      ticks: 1960
      speed: 2030
      load: -257
    center:
      ticks: 1462
      speed: 0
      load: 0
    max:
      ticks: 2315
      speed: 0
      load: -1010
    home:
      ticks: 2013
      speed: 0
      load: -2115