/**:
  ros__parameters:
    ompl:
      planner_configs:
        SBLkConfigDefault:
          type: geometric::SBL
          range: 0.0  # Max motion added to tree. ==> maxDistance_ default: 0.0, if 0.0, set on setup()
        ESTkConfigDefault:
          type: geometric::EST
          range: 0.0  # Max motion added to tree. ==> maxDistance_ default: 0.0, if 0.0, set on setup()
          goal_bias: 0.05  # When close to goal select goal, with this probability. default: 0.05
        RRTkConfigDefault:
          type: geometric::RRT
          range: 0.0  # Max motion added to tree. ==> maxDistance_ default: 0.0, if 0.0, set on setup()
          goal_bias: 0.05  # When close to goal select goal, with this probability? default: 0.05
        RRTConnectkConfigDefault:
          type: geometric::RRTConnect
          range: 0.0  # Max motion added to tree. ==> maxDistance_ default: 0.0, if 0.0, set on setup()
        RRTstarkConfigDefault:
          type: geometric::RRTstar
          range: 0.0  # Max motion added to tree. ==> maxDistance_ default: 0.0, if 0.0, set on setup()
          goal_bias: 0.05  # When close to goal select goal, with this probability? default: 0.05
          delay_collision_checking: 1  # Stop collision checking as soon as C-free parent found. default 1

      arm:
        default_planner_config: RRTConnectkConfigDefault
        planner_configs:
          - SBLkConfigDefault
          - ESTkConfigDefault
          - RRTkConfigDefault
          - RRTConnectkConfigDefault
          - RRTstarkConfigDefault
        projection_evaluator: joints(shoulder_pan_joint,shoulder_lift_joint)
        longest_valid_segment_fraction: 0.01

      gripper:
        default_planner_config: RRTConnectkConfigDefault
        planner_configs:
          - SBLkConfigDefault
          - ESTkConfigDefault
          - RRTkConfigDefault
          - RRTConnectkConfigDefault
          - RRTstarkConfigDefault
