/**:
  ros__parameters:
    move_group:
      # This is the primary planning plugin that the move_group node will load.
      # This parameter must be here for the planning pipeline to initialize.
      planning_plugin: ompl_interface/OMPLPlanner
      
      # A list of planning pipelines to use. The 'ompl' pipeline is standard
      # and references the 'ompl' namespace defined below.
      planning_pipelines: ['ompl']
      
      # Request adapters are pre-processing steps before planning.
      # They can fix the start state, add time optimal parameterization, etc.
      request_adapters: >-
        default_planner_request_adapters/AddTimeOptimalParameterization
        default_planner_request_adapters/FixWorkspaceBounds
        default_planner_request_adapters/FixStartStateBounds
        default_planner_request_adapters/FixStartStateCollision
        default_planner_request_adapters/FixStartStatePathConstraints
      
      # Response adapters are post-processing steps after planning.
      # They can validate the solution or add time optimal parameterization.
      response_adapters: >-
        default_planner_response_adapters/AddTimeOptimalParameterization
        default_planner_response_adapters/ValidateSolution
    
    # This namespace contains the configuration for the OMPL plugin itself.
    ompl:
      # This is the new line we need to add. It tells the 'ompl' planning
      # pipeline to use the OMPLPlanner C++ class.
      planning_plugin: ompl_interface/OMPLPlanner

      # This is the list of specific planners that will be used.
      # The names here must match the keys below.
      planner_configs:
        - RRTConnectkConfigDefault
        - RRTstarkConfigDefault
        - PRMstarkConfigDefault
        - RRTkConfigDefault
        - RRTstarkConfigDefault
      
      # Detailed configuration for each planner.
      RRTConnectkConfigDefault:
        type: geometric::RRTConnect
        range: 0.0
        longest_valid_segment_fraction: 0.05
        max_nearest_neighbors: 100
      
      RRTstarkConfigDefault:
        type: geometric::RRTstar
        range: 0.0
        longest_valid_segment_fraction: 0.05
        max_nearest_neighbors: 100
      
      PRMstarkConfigDefault:
        type: geometric::PRMstar
        range: 0.0
        longest_valid_segment_fraction: 0.05
        max_nearest_neighbors: 100
      
      RRTkConfigDefault:
        type: geometric::RRT
        range: 0.0
        longest_valid_segment_fraction: 0.05
        max_nearest_neighbors: 100
