/**:
  ros__parameters:
    planning_pipelines:
      - name: ompl
        kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
    planning_plugin: ompl_interface/OMPLPlanner
    request_adapters: >-
      default_planner_request_adapters/AddTimeOptimalParameterization
      default_planner_request_adapters/FixWorkspaceBounds
      default_planner_request_adapters/FixStartStateBounds
      default_planner_request_adapters/FixStartStateCollision
      default_planner_request_adapters/FixStartStatePathConstraints
    response_adapters: >-
      default_planner_response_adapters/AddTimeOptimalParameterization
      default_planner_response_adapters/ValidateSolution
      default_planner_response_adapters/DisplayRandomValidPath
